// This file is auto-generated with postcss-ts-classnames.

export type ClassNames =
  | "-z-[1]"
  | "-z-[5]"
  | "_acrylicButton"
  | "_gradientBackground"
  | "_logoBorder"
  | "_mountainLeft"
  | "_mountainMiddle"
  | "_mountainRight"
  | "_navbar"
  | "_navbarLink"
  | "_selected"
  | "aspect-square"
  | "bg-dark"
  | "block"
  | "bottom-0"
  | "container"
  | "fixed"
  | "flex"
  | "flex-col"
  | "h-1"
  | "h-1/4"
  | "h-56"
  | "invisible"
  | "items-center"
  | "justify-around"
  | "justify-center"
  | "left-0"
  | "mt-56"
  | "object-cover"
  | "p-8"
  | "place-content-center"
  | "pointer-events-none"
  | "px-8"
  | "py-2"
  | "radial-border"
  | "relative"
  | "rounded-full"
  | "solid-background"
  | "subtitle"
  | "text-center"
  | "text-dark-accent"
  | "text-light-accent"
  | "top-3"
  | "top-3/4"
  | "w-full";

export default ClassNames;
